version: "3.9"

services:
  db:
    image: postgres:12-alpine
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: "no"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

volumes:
  pg_data: