apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-demo
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75