apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-demo
  labels:
    app: express-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-demo
  template:
    metadata:
      labels:
        app: express-demo
    spec:
      containers:
      - name: express-demo
        image: juniyadi/express-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
        env:
        - name: APP_NAME
          value: "express"