apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Real-IP $remote_addr";
      more_set_headers "X-Forwarded-For $proxy_add_x_forwarded_for";
      more_set_headers "X-Forwarded-Proto $scheme";
      more_set_headers "X-Forwarded-Host $host";

spec:
  rules:
  - host: express.demo.juniyadi.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-demo
            port:
              number: 3000