apiVersion: v1
kind: Service
metadata:
  name: express-demo
  labels:
    app: express-demo
spec:
  selector:
    app: express-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4000